POST https://videos-manager.onrender.com/videos
Content-Type: application/json

{
    "title": "Comece por aqui!",
    "description": "Este vídeo é destinado a usuários que se cadastraram agora ou aos que desejam saber mais sobre a nossa plataforma e como ela funciona.",
    "duration": 420
}

###

GET https://videos-manager.onrender.com/videos

###

PUT https://videos-manager.onrender.com/videos/36011bbe-bf81-41a4-b001-7304a135e145
Content-Type: application/json

{
    "title": "O começo de tudo!",
    "description": "Este vídeo é destinado a usuários que se cadastraram agora ou aos que desejam saber mais sobre a nossa plataforma e como ela funciona.",
    "duration": 480
}

### 

DELETE https://videos-manager.onrender.com/videos/36011bbe-bf81-41a4-b001-7304a135e145